version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: carbon_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: carbon_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./models/db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
